package com.example.petstagram.UiData

import android.content.Context
import androidx.media3.common.MediaItem
import androidx.media3.common.Player
import androidx.media3.exoplayer.ExoPlayer
import com.example.petstagram.guardar.SavePressed
import com.example.petstagram.like.Pressed
import java.time.Instant
import java.util.Date

open class Post ()
{

    /**id of the document in the DB*/
    var id : String = ""
    /**title of the post TODO still not shown in UI*/
    var title : String = ""
    /**user that posted it*/
    var creatorUser: Profile? = null
    /**category this post is at*/
    var category : Category?= null
    /**type of media in this post, by now it can only be image or video*/
    var typeOfMedia:String = ""
    /**date the post was posted, autogenerated on create*/
    var postedDate : Date = Date.from(Instant.now())
    /**URL reference to the media of the post*/
    var source : String = ""
    /***/
    var likes : MutableList<Like> = mutableListOf()
    /***/
    var comments : MutableList<String> = mutableListOf()

}

class UIPost: Post() {
    var liked = Pressed.False
    var saved = SavePressed.No
    var UIsource : MediaItem = MediaItem.EMPTY
    var player : ExoPlayer?=null

    fun loadSource(context : Context){

        UIsource =MediaItem.fromUri(this.source)
        player = ExoPlayer.Builder(context).build()
        player!!.setMediaItem(UIsource)
        player!!.repeatMode = Player.REPEAT_MODE_ALL
        player!!.trackSelectionParameters = player!!.trackSelectionParameters.buildUpon().setMaxVideoFrameRate(60).setMaxVideoSize(500, 500).build()
        player!!.playWhenReady = false
        player!!.prepare()
    }
}