package com.example.petstagram.UiData

import android.content.Context
import android.net.Uri
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.media3.common.MediaItem
import androidx.media3.common.Player
import androidx.media3.exoplayer.ExoPlayer
import com.example.petstagram.guardar.SavePressed
import com.example.petstagram.like.Pressed
import java.time.Instant
import java.util.Date

open class Post ()
{

    /**id of the document in the DB*/
    var id : String = ""
    /**title of the post TODO still not shown in UI*/
    var title : String = ""
    /**user that posted it*/
    var creatorUser: Profile? = null
    /**category this post is at*/
    var category : Category?= null
    /**type of media in this post, by now it can only be image or video*/
    var typeOfMedia:String = ""
    /**date the post was posted, autogenerated on create*/
    var postedDate : Date = Date.from(Instant.now())
    /**URL reference to the media of the post*/
    var source : String = ""
    /***/
    var likes : MutableList<Like> = mutableListOf()
    /***/
    var comments : MutableList<String> = mutableListOf()
    var reports : MutableList<Report> = mutableListOf()

}

class UIPost: Post() {
    var liked = Pressed.False
    var saved = SavePressed.No
    var UIURL : Uri by mutableStateOf(Uri.EMPTY)
    var mediaItem: MediaItem by mutableStateOf(MediaItem.EMPTY)

    fun basePost():Post{
        return Post().apply {
            this.id = this@UIPost.id
            this.title = this@UIPost.title
            this.creatorUser = this@UIPost.creatorUser
            this.category = this@UIPost.category
            this.typeOfMedia = this@UIPost.typeOfMedia
            this.postedDate =this@UIPost.postedDate
            this.source = this@UIPost.source
            this.likes = this@UIPost.likes
            this.comments = this@UIPost.comments
        }
    }

}